Slack integration
ironsharkde/eyewitness pull request #3
Opened 2018-06-19 12:04 UTC by toser

have phun :)

2018-06-28 09:30 UTC, TUNER88 reviewed
Awesome contribution 👍

2018-06-28 09:30 UTC, TUNER88 commented on src/backend/witness/slack/slackbot.js
> +      // console.log('new DATA: ------> ', data)
Could you remove it please?

2018-07-04 15:28 UTC, thbaumbach commented
Tested. Nice work 👍 

A small hint about the Slack feature within the README would be cool.

2018-07-09 09:47 UTC, Bastl34 commented
quick code review: LGTM

2018-07-09 09:54 UTC, thbaumbach requested changes

2018-07-09 09:54 UTC, thbaumbach commented on src/frontend/components/Slackbot/Log.js
> +            <span className="slackbot__log-stamp">{moment(stamp).format('HH:mm:ss')}]</span>{' '}
missing `[` before the timestamp

2018-07-10 21:37 UTC, toser commented on src/frontend/components/Slackbot/Log.js
> +            <span className="slackbot__log-stamp">{moment(stamp).format('HH:mm:ss')}]</span>{' '}
yep. it was intentional..

![image](https://user-images.githubusercontent.com/11678832/42538982-d64694dc-8499-11e8-8ece-cac9452eff07.png)

2018-07-11 06:19 UTC, thbaumbach commented on src/frontend/components/Slackbot/Log.js
> +            <span className="slackbot__log-stamp">{moment(stamp).format('HH:mm:ss')}]</span>{' '}
it looks weird imho

anyway, if the other guys are ok with the current state then LGTM
@Bastl34 @TUNER88

2018-07-12 09:47 UTC, Bastl34 commented on src/frontend/components/Slackbot/Log.js
> +            <span className="slackbot__log-stamp">{moment(stamp).format('HH:mm:ss')}]</span>{' '}
I'm ok with this

2018-07-12 16:49 UTC, Bastl34 approved these changes

2018-07-13 12:25 UTC, thbaumbach approved these changes

2018-07-13 12:26 UTC, merged

2018-07-13 12:26 UTC, thbaumbach commented
Thank you 👍